version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: tejasayya7/chatback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:8080"
    environment:
      - SPRING-DATA-MONGODB_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    networks:
      - app-network


  react-service:
    image: tejasayya7/chatfront
    build:
      context: ../chat-front
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
    - REACT_APP_API_URL=http://localhost:5174
    networks:
      - app-network

volumes:
  mongo-db:

networks:
  app-network: